{% set name = "tesspy" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06c58fae63125184994ebeaedbea4f4023d5930d466a3218cd8be070f1c93079

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - geopandas >=0.10.0
    - h3-py
    - hdbscan
    - mercantile
    - osmnx
    - python >=3.7
    - scikit-learn
    - scipy

test:
  imports:
    - tesspy

about:
  home: https://github.com/siavash-saki/tesspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Tessellation of Urban Areas
  doc_url: https://tesspy.readthedocs.io
  dev_url: https://github.com/siavash-saki

extra:
  recipe-maintainers:
    - siavash-saki
